[project]
name = "excel_tk_app"
version = "0.1.0"
description = "A Tkinter + xlwings desktop app to read Excel files"
readme = "README.md"
dependencies = [
    "ruff==0.11.2",
    "xlwings==0.33.11",
]