@startuml
skinparam classAttributeIconSize 0

' === FEATURE SERVICES PACKAGE ===

package "Adapters" {
}

package "Feature Services" {
    package "Renaming" {
        class RenamingService {
            + cascade_name_cell(new_name: str): void
        }
    }
}

' === CORE SERVICES ===
package "Core Services" {
}


' === DEPENDENCIES ===
RenamingService --> "Core Services"
RenamingService --> "Adapters"

@enduml
