@startuml
skinparam defaultTextAlignment center
actor User
node "User System" {
    node "SpreadsheetXplorer" {
        node "GUI"
        node "Adapters" {
            node "Excel Adapters\nwith xlwings" as xlwings
            node "Adapters for other\nspreadsheet applications" as lib
        }
        node "Other Internal Components\n(Controller, Services, ...)" as _internal
    }

    node "Excel" {
        artifact "Excel Workbook"
    }

    cloud {
        node "Other Spreadsheet\nApplication" {
            artifact "Workbook"
        }
    }
}





User --> GUI
xlwings <--> Excel : Runtime API
lib <..> "Other Spreadsheet\nApplication" : Runtime API
GUI -[hidden]-> "Adapters"

GUI <-left-> _internal
_internal <-down-> "Adapters"
@enduml